### ISSUE TITLE
运行vanilla-knn-mt-visual出错

### ISSUE THREAD

**Issue by Old-Young233** [NJUNLP/knn-box#5]
![image](https://user-images.githubusercontent.com/33386155/203287849-401db44c-31d5-48cc-aba7-0298e1059114.png)
当我运行可视化的knn-mt出现上图的参数不匹配的错误：
第363行的参数列表：
![image](https://user-images.githubusercontent.com/33386155/203288672-167002e7-60c8-4b07-b87b-15561378015f.png)
第1153行的参数列表：
![image](https://user-images.githubusercontent.com/33386155/203288857-95a8419a-ee1a-4ca6-a01e-033b4d15b541.png)

**Comment by Old-Young233** [comment]
另外我想问一下此项目是只支持fastbpe吗，sentencepiece和subword-nmt支持吗？

**Comment by ZhaoQianfeng** [comment]
**报错**：我猜你的model_cofigs.yml配置文件里arch写成vanilla_knn_mt@xxx了,应该是vanilla_knn_mt_visual@xxx。

**分词**: 在你提问的时候，可视化展示是只能用fastbpe的。不过现在已经支持sentencepiece和subword-nmt了，你可以pull下最新代码，在model_configs.yml里通过bpe选项指定即可。比如下面的配置使用subword_nmt做子词切分:
```yml
DE-EN[it]:
  data_path: /data1/zhaoqf/0101/knn-box/data-bin/it
  model_path: /data1/zhaoqf/0101/knn-box/pretrain-models/wmt19.de-en/wmt19.de-en.ffn8192.pt
  arch: vanilla_knn_mt_visual@transformer_wmt19_de_en
  knn_mode: inference
  knn_datastore_path: /data1/zhaoqf/0101/knn-box/datastore/vanilla-visual/it
  user_dir: /data1/zhaoqf/0101/knn-box/knnbox/models
  bpe: subword_nmt
  bpe_codes: <your subword code file>
  beam: "4"
  lenpen: "0.6"
  max_len_a: "1.2"
  source_lang: de
  target_lang: en
  max_tokens: "1024"
  scoring: sacrebleu
  tokenizer: moses
```
